### ISSUE TITLE
Create a Kotlin CLI

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#252] opened 2020-05-19 06:28 UTC
We should provide a command line interface to basically execute queries, create a database, a resource and to drop resources and databases, retrieve the history of a resource...

**Comment by ManfredNentwig** [comment] 2020-05-19 16:14
I want to pick up this ticket, but have some questions.
Due I can not find an existing implemention of an CLI. 

So this is an complete new implementation, right?
If yes, is an Specification provided somewhere?

**Comment by JohannesLichtenberger** [comment] 2020-05-19 16:26
No, but basically you should be able to

- Create/Drop databases
- Create/Drop resources in a database
- Execute a query
- Simply dump a resource in one or all revisions into a JSON or XML file (depending on the database type)
- Update a resource

**Comment by JohannesLichtenberger** [comment] 2020-05-19 16:32
Maybe we can create a simple Kanban project and split this into several tasks...

**Comment by mosheduminer** [comment] 2020-05-19 16:45
Hey @ManfredNentwig, I wrote a shell using the REST-API and the python client ([here](https://gist.github.com/mosheduminer/0246058bd6f0369e0e4a9bf043221d70)). How I wrote it is not really applicable to you, but I assume that this ticket is for a CLI of similar functionality.

In my case, I used a "context", to allow shortcuts for commands. For example, `create --data []` would create a resource with `[]` as initial data, but only if the "context was already set with a database name/type and resource name. Context could be changed with commands like `database <name> <type>` and `resource <name>`.

The total commands I wrote:
```
create    delete  exists  help     info  read    repeat    root    run
database  diff    hash    history  last  record  resource  rquery  query update
```

`record` `repeat` `repeat` are shell related commands commands, and some of these other commands may not be relevant to this CLI, but maybe being aware of it helps. Feel free to reach ouut with any questions.

**Comment by ManfredNentwig** [comment] 2020-05-20 06:24
Thank you guys, I think thats help. 

One last Question: shoud I create a new Project for the CLI  or can it be part of an existing one, e. g. core?

**Comment by JohannesLichtenberger** [comment] 2020-05-20 06:56
I'd create a new module in the bundles folder `sirix-kotlin-cli`probably :-)

**Comment by ManfredNentwig** [comment] 2020-05-20 09:25
Thx. Can start now.

**Comment by JohannesLichtenberger** [comment] 2020-05-28 22:50
Any news? Do you need help? :)

**Comment by ManfredNentwig** [comment] 2020-05-29 07:08
Hi Johannes,

I did the setup and first line of code. It's fine for me at the Moment
I was busy with some other topics the last days, think I can work on these Issue the next days and will give you an update after the weekend. :-)

**Comment by ManfredNentwig** [comment] 2020-06-01 14:13
I created a branch with my first approch and my very first Kotlin code. :-)
Please have a look.


https://github.com/ManfredNentwig/sirix/tree/252_create_a_kolin_cli

**Comment by JohannesLichtenberger** [comment] 2020-06-01 14:18
Looks good :-) I'm also rather new to Kotlin, but I really like it.

**Comment by ManfredNentwig** [comment] 2020-06-07 15:07
Hi,

the create command is implemented now.
I tried out a little bit and I am not sure if I use the sirix API i a propper way but all tests are green of course. ;-)

I will implenent the next command now.

**Comment by JohannesLichtenberger** [comment] 2020-06-07 19:53
`Databases#removeDatabase` is right :-)

**Comment by JohannesLichtenberger** [comment] 2020-06-16 11:48
Did you get any further? :)

**Comment by ManfredNentwig** [comment] 2020-06-17 05:58
Jepp. :-)

I have to implement the 'Execute Query' and the 'Update update a resource' command from your list, then your List is done. I think I can finish the commands at the next weekend.

And I consider to use YML as Format for the commd file. What do you think?

**Comment by JohannesLichtenberger** [comment] 2020-06-17 08:43
Very nice, thanks a lot for all your work :+1:

**Comment by JohannesLichtenberger** [comment] 2020-07-06 17:46
Any news? :-)

**Comment by JohannesLichtenberger** [comment] 2020-07-13 16:32
@ManfredNentwig maybe you can make a PR and I can work on finishing your stuff if you might not have much time, lately? I think it's a must-have for providing a demo in a few weeks or months :+1:

**Comment by ManfredNentwig** [comment] 2020-07-14 17:36
Sorry Johannes, 
I was not able to work last time due personal reasons but I am very interested in to finisdh these task.
If I can not go on during the next weekend then it is ok for me when you ore someone else pick up these issue.

Is this ok for you?

Regards
Manfred

**Comment by JohannesLichtenberger** [comment] 2020-07-14 22:32
Sure, that's fine and totally understandable. Sorry, some issues just remain assigned to someone for months and I don't know if it's ever going to be finished. So, for sure you can have the next weekend or next couple of weekends :-) I somehow have to learn how to get status updates as in the Scrum dailies for these Github tasks. I just thought you might have disappeared, which is sadly sometimes the case. I'd certainly also hope that sometime we get more long term contributions even if not constantly, but from time to time :-) that would be awesome.

**Comment by ManfredNentwig** [comment] 2020-07-19 19:09
I complete understand the point. 
I did some work today but I haven't finish the query command today due it is more work then expected and I havn't had the time I had expected. Anyway...   I can contribute more constantly from now on. 

One Question regarding the query Command options: I copied these from the REST API but I can not see the dependencies between them. Every of them can be null but what when some of them are not null? The the query string is required but how can I validate the options? Are there any invalid combinations?


`data class QueryCommandOptions(
    val queryStr: String?,
    val resource: String?,
    val revision: Int?,
    val revisionTimestamp: LocalDateTime?,
    val startRevision: Int?,
    val endRevision: Int?,
    val startRevisionTimestamp: LocalDateTime?,
    val endRevisionTimestamp: LocalDateTime?,
    val nodeId: String?,
    val user: User?
)`

**Comment by JohannesLichtenberger** [comment] 2020-07-19 20:35
Basically valid is:

1. `revision` or
2. `revisionTimestamp` or 
3. `startRevision` and `endRevision` or
4. `startRevisionTimestamp` and `endRevisionTimestamp`

`resource` can be specified in the query so, it might be null. `nodeId` can be specified, but it doesn't have to (for serializing a subtree). `user` shouldn't be needed, I think and `queryStr` is needed for queries.

Basically everything can be addressed via the query itself, so in the case of the REST-API it's just a convenience thing :+1:

Thanks for all your work :) Maybe, it might be even okay to only use the query-command :-)

**Comment by ManfredNentwig** [comment] 2020-07-25 14:14
The query-command is implemented so far. :-)

Two issues I have:

**1. The xml xQuery Test fails with an NPE.**
I analyzed a little bit and found out, that the Method 'org.brackit.xquery.expr#processSequence' returns null due the class XmlDBNode doesn't implement Array, Record or LazySequence.  For the Json case the class JsonDbObject implements Record so that the Method returns a value.
I do not really understand this due I reused the REST Implementation and I can not see the difference. 

**2. The Help for the query-command is pritty poor**
Due I do not really understand the meaning of all parameters.  =:-o  The output of the main function with parameter 'query --help' is:

Usage: Sirix CLI query options_list
Arguments: 
    queryStr -> The Query String (optional) { String }
Options: 
    --username, -un -> The user name who interacts with the Database. Default is 'admin'. { String }
    --userid, -uid -> The user UUID. Used when the user is set. { xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx }
    --resource, -r -> The name of the resource. (always required) { String }
    --revision, -rev -> The revions to query { Int }
    --revision-timestamp, -rt -> The revision timestamp { 2020-12-20T18:44:39.464Z }
    --start-revision, -sr -> The start revision { Int }
    --end-revision, -er -> The end revision { Int }
    --start-revision-timestamp, -srt -> The start revision timestamp { 2020-12-20T18:44:39.464Z }
    --end-revision-timestamp, -ert -> The end revision timestamp { 2020-12-20T18:44:39.464Z }
    --node-id, -nid -> The node id { Long }
    --next-top-level-nodes, -ntln -> The next top level Node. Ignored for XML Databases { Int }
    --last-top-level-node-key, -ltlnk -> The last top level Node Key { Long }
    --start-result-sequence-index, -srsi -> The start Result Sequence Index { Long }
    --end-result-sequence-index, -ersi -> The end Result Sequence Index { Long }
    --max-level, -ml -> The max Level { Long }
    --meta-data, -md -> Print out meta data with the result. Ignored for XML Databases { Value should be one of [nodeKeyAndChildCount, nodeKey, all] }
    --pretty-print, -pp -> Print out formated result 
    --help, -h -> Usage info `
`

**Comment by JohannesLichtenberger** [comment] 2020-07-25 14:28
Guess I won't have time to look into it until tomorrow evening, but sounds great. You could make a PR 👍 

Another thing I'm currently investingating since two or three days and getting a bit frustrated with are test failures in the REST-API due to open resource managers found, when a request comes in to delete a resource in a database... but only on Travis or a Github Action. I haven't been able to reproduce it locally (@mosheduminer hasn't been able to reproduce it locally, too) and couldn't see open resource managers while debugging. This is really strange. Maybe it's an issue with a docker container in Docker container, when it runs on Travis or via a Github Action. I'm storing the resource managers once opened in a static final ConcurrentMap as long as the JVM is running: 

https://github.com/sirixdb/sirix/blob/45c04011104460e8fddd934a6c43b415efd9c206/bundles/sirix-core/src/main/java/org/sirix/access/Databases.java#L41

It should be closed in the database itself, when a database is closed via try-with-resources or when the resource manager itself is closed of course. Maybe you have an idea or can even reproduce it locally (sirix-rest-api tests, which need a running Keycloak container).

**Comment by ManfredNentwig** [comment] 2020-07-26 11:07
The query-command is implemented so far. :-)

Two issues I have:

**1. The xml xQuery Test fails with an NPE.**
I analyzed a little bit and found out, that the Method 'org.brackit.xquery.expr#processSequence' returns null due the class XmlDBNode doesn't implement Array, Record or LazySequence.  For the Json case the class JsonDbObject implements Record so that the Method returns a value.
I do not really understand this due I reused the REST Implementation and I can not see the difference. 

**2. The Help for the query-command is pritty poor**
Due I do not really understand the meaning of all parameters.  =:-o  The output of the main function with parameter 'query --help' is:

Usage: Sirix CLI query options_list
Arguments: 
    queryStr -> The Query String (optional) { String }
Options: 
    --username, -un -> The user name who interacts with the Database. Default is 'admin'. { String }
    --userid, -uid -> The user UUID. Used when the user is set. { xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx }
    --resource, -r -> The name of the resource. (always required) { String }
    --revision, -rev -> The revions to query { Int }
    --revision-timestamp, -rt -> The revision timestamp { 2020-12-20T18:44:39.464Z }
    --start-revision, -sr -> The start revision { Int }
    --end-revision, -er -> The end revision { Int }
    --start-revision-timestamp, -srt -> The start revision timestamp { 2020-12-20T18:44:39.464Z }
    --end-revision-timestamp, -ert -> The end revision timestamp { 2020-12-20T18:44:39.464Z }
    --node-id, -nid -> The node id { Long }
    --next-top-level-nodes, -ntln -> The next top level Node. Ignored for XML Databases { Int }
    --last-top-level-node-key, -ltlnk -> The last top level Node Key { Long }
    --start-result-sequence-index, -srsi -> The start Result Sequence Index { Long }
    --end-result-sequence-index, -ersi -> The end Result Sequence Index { Long }
    --max-level, -ml -> The max Level { Long }
    --meta-data, -md -> Print out meta data with the result. Ignored for XML Databases { Value should be one of [nodeKeyAndChildCount, nodeKey, all] }
    --pretty-print, -pp -> Print out formated result 
    --help, -h -> Usage info `
`

**Comment by ManfredNentwig** [comment] 2020-07-26 19:42
The PR is created. Nevertheless I want to implement the update command and the command file.

Unfortunately I also can't reproduce the error on my local machine and I see no reason in the code why the Tests should fail as far as I understand the code.

I am just brainstorming: 
Perhaps the thread is dead or suspended for some reasons during the tests on Travis or GitHub. In similar situations when debugging is not possible I tried to implement a logging to watch the execution tree. This can be exhausting but sometimes on these environment related issues there is no choice....

**Comment by JohannesLichtenberger** [comment] 2020-07-26 21:20
Sounds great :)

Hm, maybe logging the constructor and close calls of the resource managers will be of some help.

**Comment by JohannesLichtenberger** [comment] 2020-07-27 19:31
```
Integration test > repetition 2 of 3 STANDARD_OUT
    19:26:36.681 [vert.x-eventloop-thread-0] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xd7c2768e, L:/127.0.0.1:9443 - R:/127.0.0.1:47274] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    19:26:36.682 [vert.x-eventloop-thread-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x6aa667b7, L:/127.0.0.1:47274 - R:localhost/127.0.0.1:9443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    19:26:36.787 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Create resource: ResourceConfiguration{Resource=null, Type=MEMORY_MAPPED, Revision=SLIDING_SNAPSHOT, HashKind=ROLLING}
    19:26:36.789 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Added resource manager: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource
    19:26:36.805 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Removed resource manager: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource
    19:26:36.806 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Resource Managers left: []
    19:26:36.814 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Added resource manager: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource
    19:26:36.849 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Removed resource manager: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource
    19:26:36.849 [DefaultDispatcher-worker-1 @coroutine#370] DEBUG org.sirix.access.DatabasesInternals - Resource Managers left: []
    19:26:36.879 [vert.x-eventloop-thread-0] DEBUG io.netty.buffer.PoolThreadCache - Freed 16 thread-local buffer(s) from thread: vert.x-eventloop-thread-0
    19:26:36.880 [vert.x-eventloop-thread-3] DEBUG io.netty.buffer.PoolThreadCache - Freed 11 thread-local buffer(s) from thread: vert.x-eventloop-thread-3
Integration test > repetition 2 of 3 FAILED
    java.lang.AssertionError: org.opentest4j.AssertionFailedError: expected: <null> but was: <Failure calling the RESTful API: java.lang.IllegalStateException: Open resource managers found, must be closed first: [ResourceManager{resourceConfig=ResourceConfiguration{Resource=/home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource, Type=MEMORY_MAPPED, Revision=SLIDING_SNAPSHOT, HashKind=ROLLING}, isClosed=false}]
```

It's a damn mystery what's happening here. BTW: If you like to you can join the Slack channel :-)

**Comment by ManfredNentwig** [comment] 2020-07-28 06:18
And when the ResourceManagers where closed but not removed from the HashMap? ;-)
The check will fail in this case also.

**Comment by JohannesLichtenberger** [comment] 2020-07-28 06:34
but the one failing is not closed, have a look: https://travis-ci.org/github/sirixdb/sirix/jobs/712418666

**Comment by ManfredNentwig** [comment] 2020-07-28 07:14
Have overseen this! =:-o


In the log you send me the DEBUG Statement 'Resource managers %s for file %s' signals the call of the check.

In this log the check fails in the third iteration. Look at line 3611:

`03:24:55.934 [DefaultDispatcher-worker-3 @coroutine#344] DEBUG org.sirix.access.DatabasesInternals - Removed resource file to resource manager mapping: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource
    03:24:55.934 [DefaultDispatcher-worker-3 @coroutine#344] DEBUG org.sirix.access.DatabasesInternals - Added resource manager: /home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource
    03:24:55.963 [vert.x-eventloop-thread-0 @coroutine#346] DEBUG org.sirix.access.DatabasesInternals - Resource managers %s for file %s
    03:24:55.969 [DefaultDispatcher-worker-3 @coroutine#344] DEBUG org.sirix.access.DatabasesInternals - Removed resource manager (get): [ResourceManager{resourceConfig=ResourceConfiguration{Resource=/home/travis/build/sirixdb/sirix/bundles/sirix-rest-api/build/sirix-data/database/resources/resource, Type=MEMORY_MAPPED, Revision=SLIDING_SNAPSHOT, HashKind=ROLLING}, isClosed=false}]`
(Why my Code blocks are rendered so bad?)

The thread _DefaultDispatcher-worker-3_ just added a resource Manager and in the next line _vert.x-eventloop-thread-0_ execute the check which it does ant the end of the block in repetion 1+2.

Hope this helps....

**Comment by JohannesLichtenberger** [comment] 2020-07-28 07:50
Good catch, will have to check in the evening, but that's very strange of course and that's exactly the bug for sure. I thought the first request must have been handled.

I suppose that's whenever I call

`ctx.response().setStatusCode(200).end()`

or something like that the response is already ended and the manager is mostly closed right afterwards, but not always. Meaning I always should send the response on the main event loop, I guess or at least after everything has been closed properly.

**Comment by ManfredNentwig** [comment] 2020-07-28 07:56
So we found an X-File!  ;-)


BTW: I am not using Slack....

**Comment by ManfredNentwig** [comment] 2020-07-31 06:26
FYI: I have no time this weekend to work on the last command. Postponed to the following.

**Comment by JohannesLichtenberger** [comment] 2020-07-31 13:54
Thanks for the info and no problem :) have a nice weekend

**Comment by ManfredNentwig** [comment] 2020-08-10 06:28
FYI
Update Command is implemented, the Test not.

**Comment by JohannesLichtenberger** [comment] 2020-08-10 19:23
Sounds good :+1:

**Comment by JohannesLichtenberger** [comment] 2020-08-31 20:27
@ManfredNentwig what's the status of the client? I guess some tests are missing, but other than that it's working? 👍

**Comment by ManfredNentwig** [comment] 2020-09-01 09:40
Hi @JohannesLichtenberger ,

yes, it is implemented but the update test throws an exception regardeding the setup of the test database.
I have not had time the last weeks, but I think I can work on it next weekend again.
:-)

**Comment by JohannesLichtenberger** [comment] 2020-09-01 09:49
That's great, looking forward :-)

**Comment by ManfredNentwig** [comment] 2020-09-06 08:59
Hi Johannes,

I stuck with build errors. The master and the feature branch is merged with upstream. I haven't ave this before, any idea?

Within the IDE:
`> Task :sirix-xquery:compileJava FAILED
warning: using incubating module(s): jdk.incubator.foreign
.../sirix/bundles/sirix-xquery/src/main/java/org/sirix/xquery/json/JsonDBArray.java:15: error: JsonDBArray is not abstract and does not override abstract method append(Sequence) in Array
public final class JsonDBArray extends AbstractJsonDBArray<JsonDBArray>
 `

gradle build Commad (master):
`.../sirix/bundles/sirix-xquery/src/main/java/org/sirix/xquery/json/JsonObjectKeyDBArray.java:15: error: JsonObjectKeyDBArray is not abstract and does not override abstract method append(Sequence) in Array
public final class JsonObjectKeyDBArray extends AbstractJsonDBArray<JsonObjectKeyDBArray>
`

**Comment by JohannesLichtenberger** [comment] 2020-09-07 00:12
Hm, I've added a method to Brackit (https://github.com/sirixdb/brackit), the query processor. I think at least now it should work, if you try again!?

**Comment by JohannesLichtenberger** [comment] 2020-09-21 18:20
@ManfredNentwig do you have time to finish this?

**Comment by ManfredNentwig** [comment] 2020-09-24 06:35
@JohannesLichtenberger 
Hi Jonhannes, :-)

I implementet the Test. At the moment  the JSON updates does an an insert and the XML update throws an exception.
For me it is not clear if these is caused by the implemtation of the update or the test or by the setup of the test Database.

**Comment by JohannesLichtenberger** [comment] 2020-09-25 07:14
oh, you could disable the test, make a PR and I can have a look. Or I could clone your repo, once its pushed.

**Comment by JohannesLichtenberger** [comment] 2020-10-12 21:43
@ManfredNentwig you should be able to work on the stuff again, I've fixed the PR some time ago 👍

**Comment by ManfredNentwig** [comment] 2020-10-13 07:50
ok :-)

**Closed** 2021-12-20 19:17 UTC
